/// Prose for the Bank of Zork (``DungeonBank``): the entrance hall, the two
/// Teller's Rooms, the two Viewing Rooms, the Safety Depository with its stone
/// cube and its curtain of light, the Chairman's Office, the Small Room and the
/// Vault.
///
/// The three-way rule, and the rule for which file a line goes in, are stated
/// once on ``Prose``.
///
/// `BKEXE` and `BKVAU` are `identical` entries in
/// `docs/games/dungeon-prose-comparison.md`, so those two are the trilogy's
/// lines verbatim. `BKENT` is `minor` and adapted anyway, because the
/// mainframe's entrance hall opens south onto the Gallery and the trilogy's
/// does not. `BKBOX`, `BKVE` and `BKVW` are `substantial`: each keeps the
/// trilogy's voice and its own room's facts. The Teller's Rooms are `""` in the
/// source — their text is generated by `TELLER-ROOM` — and `BKTWI` has no
/// counterpart anywhere, so those three are written fresh, along with the cube,
/// the curtain and every wall.
extension Prose {
    // MARK: - The way in

    /// Adapted. The trilogy's Bank Entrance is a shorter line in a different
    /// building; this one is the mainframe's room, which has three doors and a
    /// bibliography.
    static let bankEntrance = """
        This is the large entrance hall of the Bank of Zork, the largest banking
        institution of the Great Underground Empire. A partial account of its
        history may be found in 'The Lives of the Twelve Flatheads', in the
        chapter on J. Pierpont Flathead; a fuller and much less objective one is
        in his own 'I'm Rich and You Aren't — So There!'. Most of the furniture
        has gone the way of passing scavengers. What is left is two signs, one
        at the northwest corner and one at the northeast, and a doorway south.
        """

    static let bankSigns = """
        Two arrows, painted with more confidence than skill:

            <--  WEST VIEWING ROOM        EAST VIEWING ROOM  -->
        """

    /// Written fresh: the source leaves both Teller's Rooms with an empty
    /// description and generates their text from `TELLER-ROOM`.
    static func tellerRoom(_ side: String) -> String {
        """
        This is the \(side) teller's station: a counter of good stone, a grille
        of good brass, and nothing at all behind either of them. A doorway leads
        north, another south, and a large one \(side) into the depository.
        """
    }

    static let tellerCounter = """
        A stone counter with a brass grille above it, and a slot at the bottom
        worn smooth by a great many hands.
        """

    /// Written fresh. Both teller's stations end by naming three doorways and
    /// the room the largest of them opens into, and neither word answered — the
    /// Bank printed `depository` ninety-nine times in one round of transcripts
    /// and denied it every time. (#332)
    static func tellerDoorways(_ side: String) -> String {
        """
        Three ways out of this station: north to the viewing room, south to the
        lobby, and the wide one \(side) that the bank's own traffic used.
        """
    }

    /// Written fresh. The Safety Depository from a teller's station — named
    /// from the doorway rather than stood in, so this is what you can see of it
    /// and not what ``safetyDepository`` says. (#332)
    static let depositoryFromTheTeller = """
        The strongroom the whole building is arranged around. From here it is a
        wide doorway and a great deal of stone, and no light of its own.
        """

    // MARK: - The Viewing Rooms

    /// Adapted. `BKVE` and `BKVW` are `substantial`, and the difference is the
    /// sign: the trilogy's teller retrieves your box, the mainframe's bank
    /// officer does, and the mainframe's notice is the one that mentions the
    /// device. One line serves both rooms, as it does in the source.
    static let viewingRoom = """
        This room was used by holders of safety deposit boxes to view their
        contents. On the north side of the room is a sign which says

            REMAIN HERE WHILE THE BANK OFFICER RETRIEVES YOUR DEPOSIT BOX.
            WHEN YOU ARE FINISHED, LEAVE THE BOX AND EXIT TO THE SOUTH.
            AN ADVANCED PROTECTIVE DEVICE PREVENTS ALL CUSTOMERS FROM
            REMOVING ANY SAFETY DEPOSIT BOX FROM THIS VIEWING AREA.

            Thank You for Banking at the Zork!
        """

    static let viewingRoomSign = """
        A notice, printed large, on the subject of what you may not leave with.
        """

    // MARK: - The Safety Depository

    /// Adapted. `BKBOX` is `substantial` and the trilogy's typography is the
    /// better of the two; the room is the same room, doorways and all.
    static let safetyDepository = """
        This is a large rectangular room. The east and west walls were used for
        storing safety deposit boxes, but all have been carefully removed by
        evil persons. To the east, west, and south of the room are large
        doorways. The northern "wall" of the room is a shimmering curtain of
        light. In the center of the room is a large stone cube, about 10 feet on
        a side. Engraved on the side of the cube is some lettering.
        """

    /// Written fresh, and the plural half of a split the round found: `x wall`
    /// answers with the curtain hanging where the north wall ought to be, and
    /// `x walls` — the two the deposit boxes came out of, which is what the
    /// room's own second sentence is about — answered nothing at all. Two
    /// different questions, and now two different answers. (#233)
    static let depositoryWalls = """
        Bare from floor to ceiling on both sides, with the fixings for a great
        many deposit boxes still in them and not one box left.
        """

    static let depositoryDoorways = """
        Three ways out of the room, all of them wide enough to carry something
        heavy through, and only the north side without one.
        """

    static let stoneCube = """
        A cube of grey stone ten feet on a side, standing in the middle of the
        floor with no visible way into it. The lettering is cut deep.
        """

    static let stoneCubeLettering = """
        Cut into the face of the cube:

                    Bank of Zork
                       VAULT
                     *722 GUE*
              Frobozz Magic Vault Company
        """

    /// The curtain from the Safety Depository, where it stands in place of the
    /// room's north wall. The room's own north refusal uses this line too, and
    /// only fires there.
    static let curtainOfLight = """
        A sheet of white light hanging where the north wall ought to be. It is
        cold, and silent, and you cannot see through it in either direction.
        """

    /// The same curtain from one of the four inner rooms it follows the player
    /// into. Those four have north walls of their own — walls the player walks
    /// through, and which ``BankInnerRoom`` maps one by one — so the line above
    /// is false in every one of them.
    static let curtainInInnerRoom = """
        A sheet of white light hanging across one side of the room. It is cold,
        and silent, and you cannot see through it in either direction.
        """

    static let curtainCarriesYou = """
        You step into the light. There is a moment with nothing in it at all,
        and then there is a floor under you again.
        """

    static let curtainHangsHere = """
        A shimmering curtain of light hangs across one side of the room. It was
        not there before you were.
        """

    static let bankAlarm = """
        An alarm rings briefly and an invisible force prevents your leaving.
        """

    // MARK: - Behind the curtain

    /// Written fresh: `BKTWI` has no counterpart in the trilogy at all.
    static let smallRoom = """
        This is a small, bare room with no distinguishing features whatsoever.
        There are no exits from this room.
        """

    /// Verbatim — `BKVAU` is `identical`.
    static let vault = """
        This is the Vault of the Bank of Zork, in which there are no doors.
        """

    /// Verbatim — `BKEXE` is `identical`.
    static let chairmansOffice = """
        This room was the office of the Chairman of the Bank of Zork. Like the
        other rooms here, it has been extensively vandalized. The lone exit is
        to the north.
        """

    static let chairmansOfficeWreckage = """
        A desk with its drawers out, a chair with three legs, and a rectangle of
        clean paint where something used to hang.
        """

    // MARK: - The walls

    static func bankWall(_ face: String) -> String {
        """
        The \(face)ern wall. It looks like stone and it sounds like stone, and
        there is nothing about it whatever to suggest that it is not.
        """
    }

    static let wallGivesWay = """
        The wall gives like water, and closes behind you.
        """

    // MARK: - The takings

    /// Adapted from the trilogy's `ODESCO`, which puts the bills on the floor
    /// rather than in mid-air. Ten to find and fifteen to case — this
    /// milestone's largest single treasure.
    static let billsFirstSight = """
        On the floor sit 200 neatly stacked zorkmid bills.
        """

    static let bills = """
        Two hundred bills, banded, each with a Flathead on the face of it and
        the promise of a Flathead on the back.
        """

    /// Adapted from the trilogy's `ODESCO`. The mainframe hangs it on the wall
    /// too, and this game keeps it there until somebody takes it down.
    static let portraitFirstSight = """
        A portrait of J. Pierpont Flathead hangs on the wall.
        """

    static let portrait = """
        J. Pierpont Flathead, in oils, at about four times life size. The
        painter has caught something about the eyes that the sitter cannot have
        been shown before he paid.
        """
}
