import Foundation
import Testing

/// The prose conventions that can only be checked by reading source. Three
/// rules in two sweeps: one about how a line names a thing, two about how a
/// literal is spelled.
///
/// ## Naming
///
/// `GameText.Line.naming { }` hands its closure a **rendered noun phrase** —
/// "the troll", "a troll", "Mrs. Vane" — not a bare name. The article is the
/// engine's, chosen from the `properName` trait, and the capitalization is the
/// line's, which is why `GameText.Noun.sentenceCased` exists. A line that opens
/// on the phrase and forgets it prints "the patrolman looks at you and does not
/// answer."
///
/// Nothing else in the toolchain can see this. `swift-format` has no rule of
/// the shape; the bootstrap's nearest diagnostic
/// (`Bootstrap.swift`, the capitalized-`name`-without-`properName` warning)
/// catches the *article* problem and is blind to the capitalization one,
/// because at bootstrap there is no line to read. The defect is invisible to
/// the test suite too, since five of Fulminate's six actors carry `properName`
/// and capitalize themselves — the transcripts look right until the one actor
/// who doesn't says his line.
///
/// So this reads `Sources/`. That is unusual enough to justify: the alternative
/// was a play-test round noticing, which costs a fan-out of agents and only
/// works if one of them happens to remember the convention. A regex is the
/// strictly better detector, and belongs where CI already runs.
///
/// **Scope, stated honestly.** The sweep only rules inside `.naming { }`
/// closure bodies, because that is the only context where `$0` is known to be a
/// rendered phrase. Elsewhere `$0` is a `String` word, a map element or an
/// `EntityID`, and the same spelling is correct. Within that scope it is
/// deliberately strict: *every* sentence-initial interpolation must be
/// sentence-cased.
///
/// ## Spelling
///
/// A line of prose is **one literal**: no trailing `\`, no `+` joining a string
/// literal to what is beside it. `TextWrap` folds a paragraph's soft newlines on
/// every channel, so a hard-wrapped literal and a one-line one render the same
/// and neither spelling buys anything.
///
/// Both were workarounds for a fold that only the full-screen channel used to
/// do, and 448 of the first survived that fix as pure noise. Nothing else can
/// see them either: `.swift-format` is generated by Persnicket and gitignored,
/// so there is nowhere to add a rule, and `swift-format` has none of this shape.
/// The bootstrap can't — the jetty's text is a `describe { }` closure, and a
/// live-text closure has no string to inspect outside a turn frame. And the
/// suite can't: the rendered output is *identical* either way, which is the
/// whole point of the fold and exactly what makes the defect invisible to a
/// transcript test.
///
/// **Scope, stated honestly.** These two rule only on the game targets, named in
/// `proseTargets`. A trailing `\` is correct in the engine's JSON-RPC frames,
/// MCP tool descriptions and `fatalError` diagnostics, none of which is ever
/// routed through `TextWrap`.
struct ProseConventionTests {
    // MARK: - The sweep

    /// Every `.naming` closure in the package sentence-cases the phrase it
    /// opens on, and none of them writes its own article.
    @Test func namingClosuresSentenceCaseThePhraseTheyOpenOn() throws {
        let sources = try Self.swiftAndDocSources()
        #expect(
            sources.count > 100,
            "the sweep found \(sources.count) files, which means it is not reading Sources/")

        var found: [Violation] = []
        for source in sources {
            found += Self.violations(in: source.text, path: source.path)
        }

        #expect(
            found.isEmpty,
            """
            A `.naming` closure opens a sentence on a rendered noun phrase \
            without sentence-casing it, or writes an article the engine \
            already supplied:

            \(found.map(\.description).joined(separator: "\n"))
            """)
    }

    /// No game target builds a line of prose out of pieces: no trailing `\` in
    /// a `"""` literal, no `+` joining a string literal to what is beside it.
    @Test func proseIsOneLiteral() throws {
        let sources = try Self.swiftAndDocSources().filter { Self.isProseTarget($0.path) }
        #expect(
            sources.count > 40,
            """
            the two rules read \(sources.count) files, which means `proseTargets` \
            no longer names the game targets
            """)

        var found: [Violation] = []
        for source in sources {
            found += Self.proseViolations(in: source.text, path: source.path)
        }

        #expect(
            found.isEmpty,
            """
            Prose is composed rather than written. `TextWrap` folds a paragraph's \
            soft newlines on every channel, so a hard-wrapped literal and a \
            one-line one render the same — neither spelling below buys anything, \
            and both were workarounds for a fold that only one channel used to do:

            \(found.map(\.description).joined(separator: "\n"))
            """)
    }

    // MARK: - The detector's own tests

    /// The sweep above passes vacuously if the detector matches nothing, which
    /// is the way a check like this rots. These pin its two directions against
    /// the real defects that motivated it.
    @Test func theDetectorCatchesBothDirectionsOfTheFault() {
        // The live Fulminate defect: correct article, lowercase sentence.
        let bare = #"""
            text.greets = .naming {
                "\($0) \($0.verb("looks", "look")) at you and does not answer."
            }
            """#
        #expect(Self.violations(in: bare, path: "x.swift").count == 1)

        // The case `CLAUDE.md` names: the line writes an article of its own,
        // so a `properName` actor becomes "the Mrs. Vane".
        let article = #"""
            text.cantTake = .naming { "The \($0) is not yours to take." }
            """#
        #expect(Self.violations(in: article, path: "x.swift").count == 1)

        // A sentence opening after a full stop inside one literal.
        let midLiteral = #"""
            text.locked = .naming { "You try it. \($0) does not give." }
            """#
        #expect(Self.violations(in: midLiteral, path: "x.swift").count == 1)

        // A field of a two-noun role struct is a rendered phrase too.
        let role = #"""
            text.given = .naming { "\($0.recipient) takes it without a word." }
            """#
        #expect(Self.violations(in: role, path: "x.swift").count == 1)
    }

    /// The spellings that must stay silent. Each is a real shape from the
    /// package, and each was a false positive in an earlier draft of the sweep.
    @Test func theDetectorPassesTheCorrectSpellings() {
        let good = [
            // The idiomatic form.
            #"text.locked = .naming { "\($0.sentenceCased) \($0.verb("is", "are")) locked." }"#,
            // Sentence-cased field of a role struct.
            #"text.given = .naming { "\($0.recipient.sentenceCased) says nothing." }"#,
            // The phrase mid-sentence needs no capital and no article.
            #"text.cantBurn = .naming { "You can't burn \($0)." }"#,
            // A verb call never opens a sentence, and carries parentheses that
            // the interpolation reader must not mistake for a phrase.
            #"text.food = .naming { "\($0.sentenceCased) \($0.verb("is", "are")) not food." }"#,
            // `$0` outside a `.naming` closure is not a rendered phrase: these
            // are a parser word, a map element and an identifier.
            #"text.unknownWord = { "I don't know the word \"\($0)\"." }"#,
            #"let names = missing.map { "\"\($0)\"" }.joined(separator: ", ")"#,
            #"let id = namespace.map { EntityID("\($0).\(label)") } ?? EntityID(label)"#,
            // `Aboard.place` is a room name held as a plain `String`, and
            // rooms are capitalized already — the room-title line opens on it
            // and is correct.
            #"text.locationInVehicle = .naming { "\($0.place), in \($0.vehicle)" }"#,
            // An article before something that is not a rendered phrase: an
            // adjective, and a word fragment.
            #"static func button(_ shape: String) -> String { "A \(shape) button, worn smooth." }"#,
            #"static func wall(_ face: String) -> String { "The \(face)ern wall." }"#,
            // A closure nested *inside* a naming body rebinds `$0`, so the
            // inner one is not the rendered phrase and the sweep must not
            // rule on it. This is `GameText.missingTopic` verbatim, which the
            // sweep reported as a fault until it counted depth.
            #"""
            text.missingTopic = .naming {
                let object = $0.object.map { " \($0)" } ?? ""
                return "What do you want to \($0.verb)\(object)?"
            }
            """#,
        ]
        for line in good {
            #expect(
                Self.violations(in: line, path: "x.swift").isEmpty,
                "false positive on: \(line)")
        }
    }

    // MARK: - The prose-spelling detector

    /// The targets whose `"""` literals are game prose end to end, and the only
    /// ones the two prose-spelling rules run on.
    ///
    /// Spelled out, and deliberately not "everything that isn't `Gnusto`". A
    /// trailing `\` is *correct* in three places under `Sources/`:
    /// `Gnusto/Playtest/` writes JSON-RPC frames and MCP tool descriptions,
    /// `Gnusto/Engine/` and `GnustoScoring/` write `fatalError` and bootstrap
    /// diagnostics, and `GnustoMacros/` writes macro diagnostics. None of those
    /// is ever routed through `TextWrap`, so none of them has a fold to depend
    /// on and the continuation is load-bearing. A game target added tomorrow and
    /// not named here goes unswept: a miss, never a false alarm.
    private static let proseTargets: Set<String> = [
        "CloakOfDarkness", "Dungeon", "Fulminate", "Gramarye",
        "KindlyDeep", "Lighthouse", "Zork1",
    ]

    /// Whether a `Sources/`-relative path is inside a game target.
    private static func isProseTarget(_ path: String) -> Bool {
        path.split(separator: "/").first.map { proseTargets.contains(String($0)) } ?? false
    }

    /// The two prose-spelling rules, run line by line.
    ///
    /// A separate pass from the `.naming` sweep above rather than another arm of
    /// it: that one rules on the *inside* of a literal and hangs off the `\(`
    /// scan, and neither of these questions is about an interpolation at all.
    private static func proseViolations(in text: String, path: String) -> [Violation] {
        // The scope is part of the detector, not of its caller: the same bytes
        // are a fault in a game target and correct in the engine, so a rule that
        // ran everywhere and was filtered afterwards would be a rule nobody
        // could test.
        guard isProseTarget(path) else { return [] }

        var found: [Violation] = []
        var inMultilineLiteral = false

        for (offset, raw) in text.components(separatedBy: .newlines).enumerated() {
            let number = offset + 1
            let line = stripComment(raw)

            // Same fence bookkeeping as the sweep above: whether *this* line is
            // inside a literal is decided before the fence on it is counted.
            let wasInside = inMultilineLiteral
            if line.contains("\"\"\"") {
                let fences = line.components(separatedBy: "\"\"\"").count - 1
                if fences % 2 == 1 { inMultilineLiteral.toggle() }
            }

            // Rule A, on `raw` rather than `line`: a prose line may contain
            // `//`, and `stripComment` would take the rest of it away.
            if wasInside, endsWithOddBackslash(raw) {
                found.append(
                    Violation(
                        path: path, line: number, excerpt: raw,
                        fault: """
                            a prose literal continues with `\\`, which folds the newline \
                            the engine would have folded anyway
                            """))
                continue
            }
            guard !wasInside else { continue }

            // Rule B. A `"""` opened on this line hides its own quotes from the
            // span splitter, so the text before the fence is checked directly.
            if let fence = line.range(of: "\"\"\"") {
                if line[..<fence.lowerBound].trimmingCharacters(in: .whitespaces).hasSuffix("+") {
                    found.append(concatenation(path: path, line: number, excerpt: raw))
                }
                continue
            }
            let spans = Self.spans(of: line)
            for (index, span) in spans.enumerated() where span.kind == .code {
                let code = span.text.trimmingCharacters(in: .whitespaces)
                let joinsNext = code.hasSuffix("+") && index + 1 < spans.count
                let joinsPrevious = code.hasPrefix("+") && index > 0
                if joinsNext || joinsPrevious {
                    found.append(concatenation(path: path, line: number, excerpt: raw))
                    break
                }
            }
        }
        return found
    }

    /// Whether a line ends in a line continuation — an *odd* run of backslashes,
    /// so an escaped backslash at the end of a line is not one.
    private static func endsWithOddBackslash(_ line: String) -> Bool {
        line.reversed().prefix(while: { $0 == "\\" }).count % 2 == 1
    }

    private static func concatenation(path: String, line: Int, excerpt: String) -> Violation {
        Violation(
            path: path, line: line, excerpt: excerpt,
            fault: "prose is joined with `+`; interpolate it into one literal instead")
    }

    // MARK: - The prose-spelling detector's own tests

    /// The same anti-rot requirement the `.naming` detector carries: both rules
    /// pinned against the real spellings the sweep of #297 deleted, and against
    /// the path scope, which is the part most likely to rot into a vacuous pass.
    @Test func theProseDetectorCatchesBothSpellings() {
        // Rule A: the jetty, as PR #297 proposed to write it.
        let continued = #"""
            let body = """
                A short timber jetty on stone footings runs out from the foot of \
                the lighthouse to the mooring where the keeper's boat rides.
                """
            """#
        #expect(
            Self.proseViolations(in: continued, path: "Lighthouse/Lighthouse.swift").count == 1)

        // Rule B, both shapes: literal onto a value, and literal onto literal.
        let ontoValue = #"return body + " The tide is low, the planks dry underfoot.""#
        #expect(
            Self.proseViolations(in: ontoValue, path: "Lighthouse/Lighthouse.swift").count == 1)

        let ontoLiteral = #""Your score is \(score), " + "in \(moves) turns.""#
        #expect(Self.proseViolations(in: ontoLiteral, path: "Zork1/Zork1.swift").count == 1)

        // Rule B across lines, which is how every site in the package was
        // written: the `+` leads the continuation line.
        let leadingPlus = #"""
            say(
                "Your score is \(score), "
                    + "in \(moves) turns.")
            """#
        #expect(Self.proseViolations(in: leadingPlus, path: "Zork1/Zork1.swift").count == 1)

        // And onto a `"""` literal, where the fence hides the quotes.
        let ontoMultiline = #"""
            try reply(
                scene + " "
                    + """
                    Biscuit watches every swallow.
                    """)
            """#
        #expect(
            Self.proseViolations(in: ontoMultiline, path: "KindlyDeep/KindlyDeep.swift").count >= 1)
    }

    /// The scope, and the spellings that must stay silent. The scope test is the
    /// load-bearing one: the same bytes are a fault in a game target and correct
    /// in the engine, because only one of the two is ever routed through
    /// `TextWrap`.
    @Test func theProseDetectorRulesOnlyOnGameTargets() {
        // A JSON-RPC frame has to be one line, and never reaches `TextWrap`.
        let frame = #"""
            let request = """
                {"jsonrpc":"2.0","id":1,"method":"tools/call","params":\
                {"name":"open"}}
                """
            """#
        #expect(Self.proseViolations(in: frame, path: "Gnusto/Playtest/PlaytestTools.swift").isEmpty)
        // The identical spelling inside a game target is the fault.
        #expect(!Self.proseViolations(in: frame, path: "Dungeon/Dungeon.swift").isEmpty)

        let good = [
            // The spelling the sweep exists to produce.
            #"""
            let body = """
                A short timber jetty on stone footings runs out from the foot of
                the lighthouse to the mooring where the keeper's boat rides.
                """
            """#,
            // Interpolation, not concatenation.
            #"return "\(body) The tide is low, the planks dry underfoot.""#,
            // `+` on things that are not prose: an array of commands, a number,
            // and a route built from two arrays.
            #"let route = intoTheKitchen + ["west", "east"]"#,
            #"let next = index + 1"#,
            #"lines += wrapWords(words, width: width)"#,
            // A form: indented, so it keeps its shape, and it carries no `\`.
            #"""
            static let etchings = """
                Letters are cut round the brickwork in a ring:

                    f r o b o z z i c a
                    a                 n
                """
            """#,
            // An escaped backslash at the end of a prose line is not a
            // continuation.
            #"""
            static let dos = """
                The path reads C:\\
                and then stops.
                """
            """#,
        ]
        for source in good {
            #expect(
                Self.proseViolations(in: source, path: "Dungeon/Dungeon.swift").isEmpty,
                "false positive on: \(source)")
        }
    }

    // MARK: - Reading the package

    /// One source file the sweep read.
    private struct Source {
        let path: String
        let text: String
    }

    /// Where a fault is, and which of the two it is.
    private struct Violation: CustomStringConvertible {
        let path: String
        let line: Int
        let excerpt: String
        let fault: String

        var description: String { "\(path):\(line) — \(fault)\n    \(excerpt)" }
    }

    /// The package's `Sources/` directory, found relative to this file rather
    /// than to the working directory, which a test process does not control.
    private static var sourcesDirectory: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // GnustoTests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // the package
            .appendingPathComponent("Sources", isDirectory: true)
    }

    /// Every Swift file under `Sources/`, plus the DocC articles, whose code
    /// samples teach the convention and so have to obey it.
    private static func swiftAndDocSources() throws -> [Source] {
        let root = sourcesDirectory
        guard
            let walker = FileManager.default.enumerator(
                at: root, includingPropertiesForKeys: nil)
        else {
            Issue.record("could not read \(root.path)")
            return []
        }
        var sources: [Source] = []
        for case let url as URL in walker where ["swift", "md"].contains(url.pathExtension) {
            guard let text = try? String(contentsOf: url, encoding: .utf8) else { continue }
            sources.append(
                Source(path: url.path.replacingOccurrences(of: root.path + "/", with: ""), text: text))
        }
        return sources
    }

    // MARK: - The detector

    /// The suffixes that make a dotted expression a rendered noun phrase. `$0`
    /// itself qualifies inside a `.naming` closure, which is the only place
    /// this runs.
    private static let phraseSuffixes = ["phrase", "definiteName", "indefiniteName"]

    /// The `Noun`-typed fields of the two-thing role structs in
    /// `GameText+Line.swift` — `Holding`, `Carried`, `Gift` and `Aboard`.
    /// Deliberately not every field: `Aboard.place` is a `String`.
    private static let nounFields = ["item", "holder", "noun", "gift", "recipient", "vehicle"]

    /// The articles the engine has already supplied.
    private static let articles = ["the", "a", "an"]

    /// Rules on one file's text.
    ///
    /// Walks the source as a small state machine rather than a single regex,
    /// because the question is *positional* — the same interpolation is correct
    /// mid-sentence and wrong at the head of one — and because `$0` only means
    /// a phrase inside a `.naming` body, which needs brace tracking to find.
    private static func violations(in text: String, path: String) -> [Violation] {
        var found: [Violation] = []
        var depth = 0
        var namingDepth: Int?
        var pendingNaming = false
        var inMultilineLiteral = false

        for (offset, raw) in text.components(separatedBy: .newlines).enumerated() {
            let number = offset + 1
            let line = stripComment(raw)

            // A `"""` literal spans lines. Whether *this* line is prose is
            // decided by the state on entering it, so the fence is counted
            // after the decision and not before.
            let wasInMultilineLiteral = inMultilineLiteral
            if line.contains("\"\"\"") {
                let fences = line.components(separatedBy: "\"\"\"").count - 1
                if fences % 2 == 1 { inMultilineLiteral.toggle() }
            }

            // Inside a `"""` block the line is prose, so braces there are not
            // structure and the quote-splitter has nothing to split on. No
            // `.naming` closure in the package opens one today; this keeps the
            // sweep from going blind if one ever does. A line-leading
            // interpolation is *not* read as a sentence head here, because
            // `TextWrap` folds the newline above it into a space — so the line
            // is a continuation of the sentence before it, not a new one.
            if wasInMultilineLiteral {
                if namingDepth != nil {
                    found += faults(
                        inLiteral: line, path: path, line: number, excerpt: raw,
                        lineStartOpensASentence: false)
                }
                continue
            }

            for span in spans(of: line) {
                switch span.kind {
                case .string:
                    // Directly in the `.naming` body, and not one closure
                    // deeper. A nested closure rebinds `$0` — `missingTopic`
                    // builds its optional fragment with
                    // `$0.object.map { " \($0)" }`, where the inner `$0` is
                    // the unwrapped `String` and not the rendered phrase. The
                    // sweep's whole licence is that inside a naming body `$0`
                    // *is* a phrase; where that stops being true the sweep has
                    // to stop ruling, or it reports a fault against a spelling
                    // that is correct.
                    guard let naming = namingDepth, depth == naming + 1 else { continue }
                    found += faults(
                        inLiteral: span.text, path: path, line: number, excerpt: raw,
                        lineStartOpensASentence: true)
                case .code:
                    if span.text.contains(".naming") { pendingNaming = true }
                    for character in span.text {
                        if character == "{" {
                            if pendingNaming, namingDepth == nil {
                                namingDepth = depth
                                pendingNaming = false
                            }
                            depth += 1
                        } else if character == "}" {
                            depth -= 1
                            if let start = namingDepth, depth <= start { namingDepth = nil }
                        }
                    }
                }
            }
        }
        return found
    }

    /// Drops a trailing `//` comment, and a whole line that is only a comment,
    /// so that a doc comment quoting a bad spelling is not read as source.
    private static func stripComment(_ line: String) -> String {
        if line.trimmingCharacters(in: .whitespaces).hasPrefix("//") { return "" }
        var result = ""
        var inString = false
        var previous: Character?
        var index = line.startIndex
        while index < line.endIndex {
            let character = line[index]
            let next = line.index(after: index)
            if character == "\"", previous != "\\" { inString.toggle() }
            if character == "/", !inString, next < line.endIndex, line[next] == "/" { break }
            result.append(character)
            previous = character
            index = next
        }
        return result
    }

    /// One stretch of a line, either code or the inside of a string literal.
    private struct Span {
        enum Kind { case code, string }
        let kind: Kind
        let text: String
    }

    /// Splits a line into code and string-literal spans, so that braces in
    /// prose are not counted and `.naming` in prose is not seen.
    private static func spans(of line: String) -> [Span] {
        var spans: [Span] = []
        var current = ""
        var inString = false
        var previous: Character?
        for character in line {
            if character == "\"", previous != "\\" {
                spans.append(Span(kind: inString ? .string : .code, text: current))
                current = ""
                inString.toggle()
            } else {
                current.append(character)
            }
            previous = character
        }
        spans.append(Span(kind: inString ? .string : .code, text: current))
        return spans
    }

    /// Rules on the inside of one string literal.
    private static func faults(
        inLiteral literal: String, path: String, line: Int, excerpt: String,
        lineStartOpensASentence: Bool
    ) -> [Violation] {
        var found: [Violation] = []
        let characters = Array(literal)

        for index in characters.indices {
            guard characters[index] == "\\", index + 1 < characters.count,
                characters[index + 1] == "("
            else { continue }
            guard let expression = expression(in: characters, startingAt: index + 2) else {
                continue
            }
            guard isRenderedPhrase(expression) else { continue }

            if opensASentence(
                characters, before: index, lineStartCounts: lineStartOpensASentence)
            {
                guard !expression.hasSuffix(".sentenceCased") else { continue }
                found.append(
                    Violation(
                        path: path, line: line, excerpt: excerpt.trimmed,
                        fault: """
                            `\\(\(expression))` opens a sentence without \
                            `.sentenceCased`, so a name with no `properName` \
                            prints lowercase
                            """))
            } else if let article = article(before: characters, at: index) {
                found.append(
                    Violation(
                        path: path, line: line, excerpt: excerpt.trimmed,
                        fault: """
                            "\(article)" is written before `\\(\(expression))`, \
                            which already carries the engine's article
                            """))
            }
        }
        return found
    }

    /// Reads a dotted identifier chain up to its closing paren, or `nil` when
    /// the interpolation holds anything more complicated — a call such as
    /// `$0.verb("is", "are")` or `GameText.sentenceCase(name)`, neither of
    /// which can open a sentence wrongly.
    private static func expression(in characters: [Character], startingAt start: Int) -> String? {
        var index = start
        var text = ""
        while index < characters.count {
            let character = characters[index]
            if character == ")" { return text.isEmpty ? nil : text }
            guard character.isLetter || character.isNumber || character == "." || character == "$" || character == "_"
            else { return nil }
            text.append(character)
            index += 1
        }
        return nil
    }

    /// Whether a dotted chain names a rendered phrase.
    ///
    /// A bare `$0` qualifies because this only runs inside a `.naming` body,
    /// where the closure's argument is a `Noun`. A field of one of the
    /// two-thing role structs qualifies only if that field is *typed* `Noun`:
    /// `GameText.Aboard.place` is a plain `String` holding a room name, and
    /// room names are capitalized already, which is why the allowlist is
    /// spelled out rather than inferred. A role struct that gains a `Noun`
    /// field and is not added here goes unswept — a miss, never a false alarm.
    private static func isRenderedPhrase(_ expression: String) -> Bool {
        if expression == "$0" || expression == "$1" { return true }
        if expression.hasSuffix(".sentenceCased") { return true }
        if expression.hasPrefix("$0.") || expression.hasPrefix("$1.") {
            return nounFields.contains { expression.hasSuffix(".\($0)") }
        }
        return phraseSuffixes.contains { expression.hasSuffix(".\($0)") }
    }

    /// Whether the interpolation at `index` stands at the head of a sentence:
    /// the start of the literal, or after a full stop, or after a line break.
    private static func opensASentence(
        _ characters: [Character], before index: Int, lineStartCounts: Bool
    ) -> Bool {
        var cursor = index - 1
        var sawSpace = false
        while cursor >= 0, characters[cursor] == " " {
            sawSpace = true
            cursor -= 1
        }
        if cursor < 0 { return lineStartCounts }
        // An escaped newline inside a literal, written `\n`.
        if characters[cursor] == "n", cursor > 0, characters[cursor - 1] == "\\" { return true }
        guard sawSpace else { return false }
        return ".!?".contains(characters[cursor])
    }

    /// The article immediately before the interpolation, if a line wrote one.
    private static func article(before characters: [Character], at index: Int) -> String? {
        guard index > 0, characters[index - 1] == " " else { return nil }
        var cursor = index - 2
        var word = ""
        while cursor >= 0, characters[cursor].isLetter {
            word.insert(characters[cursor], at: word.startIndex)
            cursor -= 1
        }
        guard articles.contains(word.lowercased()) else { return nil }
        return word
    }
}

extension String {
    /// The line without its indentation, for an assertion message.
    fileprivate var trimmed: String { trimmingCharacters(in: .whitespaces) }
}
